import "./auth.tsp";
import "./headers.tsp";
import "./query.tsp";
import "./response.tsp";
import "./error.tsp";
import "./base.tsp";
import "./operation.tsp";

//
import "./enum.tsp";
import "./user.tsp";
import "./leave.tsp";
import "./request.tsp";
import "./can-permission.tsp";
import "./file.tsp";
import "./home.tsp";
import "./softever-fit.tsp";
import "./skill-up.tsp";
import "./lifestyle-wallet.tsp";
import "./permission.tsp";
import "./user-management.tsp";
import "./project-management.tsp";
