import "./auth-service.tsp";
import "./file-service.tsp";

//
import "./user-service.tsp";
import "./leave-service.tsp";
import "./home-service.tsp";
import "./softever-fit-service.tsp";
import "./skill-up-service.tsp";
import "./lifestyle-wallet-service.tsp";
import "./permission-service.tsp";
import "./user-management-service.tsp";
import "./project-management-service.tsp";
import "./payment-service.tsp";
import "./report-service.tsp";
import "./notification-service.tsp";
